.TH KEEPASSC "1" "Januar 2016" "keepassc" "KeePass commandline client"
.SH NAME
keepassc - command line interface for KeePass v4 (.kdbx) files
.SH SYNOPSIS
 \fBsearch\fP [\fIoptions\fP] <\fIkey\fP> <\fIdbfile\fP> [...]
 \fBdump\fP [\fIoptions\fP] <\fIdbfile\fP> [...]
.SH COMMANDS
Several commands and options are available.
.SS \fBsearch\fP [\fIoptions\fP] <\fIkey\fP> <\fIdbfile\fP> [...]
Searches given key in all entries in keepass databases.
The search is case insensitive and ignores deleted entries in
the backup folder. For each entry the folder name, title and
notes are searched.
.TP
\fB\-p\fP, \fB\-\-show\-passwords\fP
Also show passwords of entries.
.SS \fBdump\fP [\fIoptions\fP] <\fIdbfile\fP> [...]
Pretty print contents of keepass databases.
Output is the underlying XML structure.
.TP
\fB\-p\fP, \fB\-\-show\-passwords\fP
Show passwords in database dump.
.SH HELP OPTION
Specifying the help option displays help for keepassc itself, or a
command.
.br
For example:
  \fBkeepassc \-\-help\fP - display help for keepassc
  \fBkeepassc search \-\-help\fP - display help for the search command
.SH AUTHOR
Bastian Kleineidam <calvin@users.sourceforge.net>
.SH COPYRIGHT
Copyright \(co 2012,2016 Bastian Kleineidam
